const RASTER_RE = /\.(jpe?g|png)$/i

/** Percent-encode each path segment so filenames with spaces resolve correctly. */
function encodePath(p) {
    return p.split('/').map(encodeURIComponent).join('/')
}

/**
 * Renders a photo with modern-format <picture> sources when the src is a
 * raster original (jpg/jpeg/png) that has .avif/.webp siblings generated by
 * scripts/optimize-images.mjs. Non-raster sources (e.g. existing .webp) are
 * rendered as a plain <img>.
 *
 * All extra props (className, loading, onError, style, ...) are forwarded to
 * the inner <img>.
 */
export default function OptimizedImage({ src, alt = '', ...rest }) {
    if (!RASTER_RE.test(src)) {
        return <img src={encodePath(src)} alt={alt} {...rest} />
    }

    const base = encodePath(src.replace(RASTER_RE, ''))

    return (
        <picture>
            <source type="image/avif" srcSet={`${base}.avif`} />
            <source type="image/webp" srcSet={`${base}.webp`} />
            <img src={encodePath(src)} alt={alt} {...rest} />
        </picture>
    )
}
